// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitestore

type Block struct {
	ID      int64  `json:"id"`
	Number  *int64 `json:"number"`
	Hash    []byte `json:"hash"`
	Parent  []byte `json:"parent"`
	Payload []byte `json:"payload"`
}
