// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlitestore

import (
	"context"
)

const deleteBlocksBeforeIncluding = `-- name: DeleteBlocksBeforeIncluding :exec
DELETE FROM blocks WHERE id <= ?
`

func (q *Queries) DeleteBlocksBeforeIncluding(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBlocksBeforeIncluding, id)
	return err
}

const getBlockCount = `-- name: GetBlockCount :one
SELECT COUNT(*)
FROM blocks
`

func (q *Queries) GetBlockCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlockCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBlocksAfter = `-- name: GetBlocksAfter :many
SELECT id,
    number,
    hash,
    parent,
    payload
FROM blocks
WHERE id > ?
LIMIT ?
`

type GetBlocksAfterParams struct {
	ID    int64 `json:"id"`
	Limit int64 `json:"limit"`
}

func (q *Queries) GetBlocksAfter(ctx context.Context, arg GetBlocksAfterParams) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, getBlocksAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Hash,
			&i.Parent,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO blocks (
        number,
        hash,
        parent,
        payload
    )
VALUES (?, ?, ?, ?)
`

type InsertBlockParams struct {
	Number  *int64 `json:"number"`
	Hash    []byte `json:"hash"`
	Parent  []byte `json:"parent"`
	Payload []byte `json:"payload"`
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.ExecContext(ctx, insertBlock,
		arg.Number,
		arg.Hash,
		arg.Parent,
		arg.Payload,
	)
	return err
}
