// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlitestore

import (
	"context"
)

const deleteBlocksBeforeIncluding = `-- name: DeleteBlocksBeforeIncluding :exec
DELETE FROM blocks WHERE id <= ?
`

func (q *Queries) DeleteBlocksBeforeIncluding(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBlocksBeforeIncluding, id)
	return err
}

const getBlockCount = `-- name: GetBlockCount :one
SELECT COUNT(*)
FROM blocks
`

func (q *Queries) GetBlockCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlockCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBlocksAfter = `-- name: GetBlocksAfter :many
SELECT id,
    number,
    hash,
    parent,
    block,
    receipts,
    call_traces,
    prestate_traces,
    keccak256_preimage_traces,
    state_access_traces
FROM blocks
WHERE id > ?
`

func (q *Queries) GetBlocksAfter(ctx context.Context, id int64) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, getBlocksAfter, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Hash,
			&i.Parent,
			&i.Block,
			&i.Receipts,
			&i.CallTraces,
			&i.PrestateTraces,
			&i.Keccak256PreimageTraces,
			&i.StateAccessTraces,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO blocks (
        number,
        hash,
        parent,
        block,
        receipts,
        call_traces,
        prestate_traces,
        keccak256_preimage_traces,
        state_access_traces
    )
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBlockParams struct {
	Number                  int64  `json:"number"`
	Hash                    []byte `json:"hash"`
	Parent                  []byte `json:"parent"`
	Block                   []byte `json:"block"`
	Receipts                []byte `json:"receipts"`
	CallTraces              []byte `json:"call_traces"`
	PrestateTraces          []byte `json:"prestate_traces"`
	Keccak256PreimageTraces []byte `json:"keccak256_preimage_traces"`
	StateAccessTraces       []byte `json:"state_access_traces"`
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.ExecContext(ctx, insertBlock,
		arg.Number,
		arg.Hash,
		arg.Parent,
		arg.Block,
		arg.Receipts,
		arg.CallTraces,
		arg.PrestateTraces,
		arg.Keccak256PreimageTraces,
		arg.StateAccessTraces,
	)
	return err
}
