// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlitestore

import (
	"context"
)

const getBlockCount = `-- name: GetBlockCount :one
SELECT COUNT(*) FROM blocks
`

func (q *Queries) GetBlockCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlockCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO blocks (number, hash, parent, block, receipts, call_traces, prestate_traces, keccak256_preimage_traces, state_access_traces)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBlockParams struct {
	Number                  int64  `json:"number"`
	Hash                    []byte `json:"hash"`
	Parent                  []byte `json:"parent"`
	Block                   []byte `json:"block"`
	Receipts                []byte `json:"receipts"`
	CallTraces              []byte `json:"call_traces"`
	PrestateTraces          []byte `json:"prestate_traces"`
	Keccak256PreimageTraces []byte `json:"keccak256_preimage_traces"`
	StateAccessTraces       []byte `json:"state_access_traces"`
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.ExecContext(ctx, insertBlock,
		arg.Number,
		arg.Hash,
		arg.Parent,
		arg.Block,
		arg.Receipts,
		arg.CallTraces,
		arg.PrestateTraces,
		arg.Keccak256PreimageTraces,
		arg.StateAccessTraces,
	)
	return err
}
